version: '3'
services:
  pandora-helper:
    image: kylsky/pandora_helper_v2
    volumes:
      - db-data:/app/db
    environment:
      CLIENT_ID: ""                                   # 1.你的linux-do oauth client
      CLIENT_SECRET: ""                               # 2.你的linux-do oauth secret
      REDIRECT_URI: ""                                # 3.必填，你的应用地址
      OAIFREE_PROXY: "https://new.oaifree.com"        # 4.默认oaifree，你可以填写你的代理地址
      FUCLAUDE_PROXY: "https://demo.fuclaude.com"     # 5.默认fuclaude，你可以填写你的fuclaude地址
      TZ: "Asia/Shanghai"
      ADMIN_NAME: "Admin"                             # 6.管理员用户名，建议填写你在linux-do的用户名，默认密码是123456

    ports:
      - "8181:8181"                                   # 7.如需修改端口，请修改第一个8181为你需要访问的服务器端口
    restart: always

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/db                # 8.指定宿主机的数据库挂载目录，必须使用绝对路径
